### ISSUE TITLE
Can't use async await

### ISSUE THREAD

**Issue by 3rChuss** [ionutvmi/uglifyjs-folder#26]
Hi, I think there's another issue with terser, I could not see an issue in their github, so maybe is something that you can solve?
Using async await returns an error,

```javascript
SyntaxError: Unexpected token: name (authCurator)
    at js_error (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:550:11)
    at croak (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1274:9)    
    at token_error (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1282:9)
    at unexpected (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1288:9)
    at semicolon (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1326:56)
    at simple_statement (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1583:73)
    at statement (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1396:19)
    at _embed_tokens_wrapper (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1339:26)      
    at block_ (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:2172:20)
    at statement (D:\PROYECTOS\xx\aaAPP\cms\node_modules\terser\dist\bundle.min.js:1403:29)
```
Thanks

**Comment by ionutvmi** [comment]
Can you post a snippet of the code that causes the issue ?

The following works gets minified on my side:

```

async function main() {

	let result = await fetch("https://google.com");

	console.log("Result");
}

main();

```

**Comment by 3rChuss** [comment]
I'm sorry @ionutvmi, I did not install it globally, working with branches I was using the old version of the package. I didn't realize it until I got more errors with ECMA2021. All works ok. Thank you.
