### ISSUE TITLE
Error in terser

### ISSUE THREAD

**Issue by derPiepmatz** [ionutvmi/uglifyjs-folder#28]
Hey I wanted to use your package to minify my code, but upon running it, I get the following error:
```
> npx uglifyjs-folder dist

SyntaxError: "typescript_1" is redeclared
    at js_error (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:550:11)
    at TreeWalker.visit (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:9532:17)
    at TreeWalker._visit (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:5122:24)
    at AST_SymbolConst._walk (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:3653:24)
    at AST_VarDef.<anonymous> (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:4357:23)
    at TreeWalker._visit (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:5126:21)
    at AST_VarDef._walk (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:4356:24)
    at AST_Const.<anonymous> (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:4327:32)
    at TreeWalker._visit (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:5126:21)
    at AST_Const._walk (C:\Code-Spielplatz\pretty-ts-imports\node_modules\terser\dist\bundle.min.js:4324:24)

Process finished with exit code 1
```

Maybe it has to do with my installed packages, so you have part of my package.json here:
```json
{
  ...
  "dependencies": {
    "typescript": "^4.3.5",
    "yargs": "^17.0.1"
  },
  "devDependencies": {
    "@types/jasmine": "^3.8.2",
    "@types/node": "^16.4.11",
    "del-cli": "^4.0.1",
    "jasmine": "^3.8.0",
    "jasmine-ts": "^0.4.0",
    "ts-node": "^10.1.0",
    "uglifyjs-folder": "^3.0.0"
  }
}
```

I hope you can resolve that issue, would love to user your package. ❤️

**Comment by ionutvmi** [comment]
Do you happen to have small snippet of code that can reproduce this issue ?
I don't see any issue with the dependencies as long as you are trying to minify compiled javascript code.

**Comment by derPiepmatz** [comment]
I made a small [stackblitz project](https://stackblitz.com/edit/node-podxbj?devtoolsheight=33&file=package.json) to show the issue. The code makes not real sense but should still show the issue.

It seems that typescript likes to compile the same constant every time to the same output. Your uglifier is not able to handle these redundant names.

**Comment by ionutvmi** [comment]
I only got the chance to review this today.

Looking at the example project the minifier behaves as expected.
When the code is compiled there are some global variables like `sourceFile` and this is what causes the issues.

Have you tried to compile the code using UMD instead ?

Something like this in the tsconfig file:
```
{
  "compilerOptions": {
    "incremental": false,
    "target": "ES2021",
    "module": "UMD",
    "moduleResolution": "node",
    "outDir": "dist"
  },
  "include": ["./src"]
}
```

The output is wrapped in an IIFE and the conflicts from the global variables are resolved.
You could also experiment with other module types to find something that works for you.

**Comment by derPiepmatz** [comment]
After I've written the code for the PR, I realized, that merging all my files into isn't event what I wanted. xD
So for me this issue is resolved. If you care you can still checkout the PR #29, if you don't want it, it's fine. c:

**Comment by ionutvmi** [comment]
Good to hear that you found a solution !
