### ISSUE TITLE
SyntaxError: Unexpected token: operator (<)

### ISSUE THREAD

**Issue by Santhosh-Umapathi** [ionutvmi/uglifyjs-folder#35]
Hi, I was trying to use this package to minify my react native code. But when I tried to run the following command, it keeps throwing this error.

```uglifyjs-folder dist -e -x .js -o dist```

```bash
> uglifyjs-folder dist -e -x .js -o dist

SyntaxError: Unexpected token: operator (<)
    at js_error (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:554:11)
    at croak (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:1278:9)
    at token_error (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:1286:9)
    at unexpected (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:1292:9)
    at expr_atom (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:2531:9)
    at maybe_unary (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:3316:19)
    at expr_ops (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:3367:24)
    at maybe_conditional (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:3372:20)
    at maybe_assign (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:3449:20)
    at expression (/usr/local/lib/node_modules/uglifyjs-folder/node_modules/terser/dist/bundle.min.js:3474:24)
npm ERR! Lifecycle script `uglify` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: @rn-module/design@1.0.0 
npm ERR!   at location: /Users/santhosh-umapathi/Desktop/Playground/RN_Modularized/packages/Design 
error Command failed with exit code 1.
```

**Comment by ionutvmi** [comment]
Did you find the snippet of source code that is causing the error to be able to reproduce the use case ?

**Comment by Santhosh-Umapathi** [comment]
> Did you find the snippet of source code that is causing the error to be able to reproduce the use case?

Yes, apparently I think this was not intended to uglify the React or React Native code, but node packages. Since React, React native uses syntaxes like HTML tags (JSX), that was the cause of this error.
