### ISSUE TITLE
crash on uglify

### ISSUE THREAD

**Issue by rchovan** [ionutvmi/uglifyjs-folder#9]
Hi, 
I was already used uglify version 1.2.0 without error, but it started crashing. I don´t know why. 
Tested on Windows 10 64bit, Debian 8.9 64bit

```
uglifyjs-folder platforms/browser/www/ -e -p "**/*.js,!**openui5**/**" -x .js -o platforms/browser/www/

undefined:1555
    throw new JS_Parse_Error(message, filename, line, col, pos);
    ^
 Error
    at new JS_Parse_Error (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1547:18)
    at js_error (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:1555:11)
    at croak (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2094:9)
    at token_error (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2102:9)
    at expect_token (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2115:9)
    at expect (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2118:36)
    at eval (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2691:13)
    at eval (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2141:24)
    at expr_atom (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2621:35)
    at maybe_unary (eval at <anonymous> (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\uglify-js\tools\node.js:28:1), <anonymous>:2797:19)

```

Similar error if I want to uglify only 1 file. 
```
uglifyjs-folder platforms/browser/www/Component.js -o platforms/browser/www/Component.js
C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:327
        throw error
        ^

Error: ENOTDIR invalid cwd D:\NetBeansProjects\ReturnReporting\platforms\browser\www\Component.js
    at GlobSync._readdirError (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:324:21)
    at GlobSync._readdir (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:290:10)
    at GlobSync._processGlobStar (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:350:22)
    at GlobSync._process (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:130:10)
    at new GlobSync (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:48:10)
    at Function.globSync [as sync] (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\glob\sync.js:26:10)
    at C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\globby\index.js:78:35
    at Array.reduce (native)
    at Function.module.exports.sync (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\node_modules\globby\index.js:77:19)
    at module.exports (C:\Users\radoslav.chovan\AppData\Roaming\npm\node_modules\uglifyjs-folder\index.js:29:23)
```

npm show uglifyjs-folder

```
{ name: 'uglifyjs-folder',
  description: 'Run uglifyjs on a folder and minify the result in a single file',
  'dist-tags': { latest: '1.2.0' },
  versions: [ '0.1.0', '0.2.0', '0.2.1', '0.3.0', '1.0.0', '1.1.0', '1.2.0' ],
  maintainers: [ 'ionutvmi <ionutvmi@gmail.com>' ],
  time:
   { modified: '2017-08-27T12:01:58.272Z',
     created: '2014-01-05T22:26:10.401Z',
     '0.1.0': '2014-01-05T22:26:10.401Z',
     '0.2.0': '2014-10-12T21:50:51.471Z',
     '0.2.1': '2014-10-13T08:45:37.504Z',
     '0.3.0': '2016-10-01T08:16:47.882Z',
     '1.0.0': '2016-12-28T02:52:49.905Z',
     '1.1.0': '2017-02-06T19:17:01.029Z',
     '1.2.0': '2017-08-27T12:01:58.272Z' },
  homepage: 'https://github.com/ionutvmi/uglifyjs-folder',
  keywords: [ 'uglify', 'folder', 'directory', 'cli' ],
  repository:
   { type: 'git',
     url: 'git://github.com/ionutvmi/uglifyjs-folder.git' },
  author: 'Mihai Ionut Vilcu <ionutvmi@gmail.com>',
  bugs: { url: 'https://github.com/ionutvmi/uglifyjs-folder/issues' },
  readmeFilename: 'README.md',
  users: { ionutvmi: true, hex20dec: true },
  version: '1.2.0',
  licenses:
   [ { type: 'MIT',
       url: 'https://github.com/ionutvmi/uglifyjs-folder/blob/master/LICENSE-MIT' } ],
  engines: { node: '>= 0.10.0' },
  preferGlobal: true,
  bin: { 'uglifyjs-folder': 'cli.js' },
  scripts: { test: 'ava', coverage: 'nyc --reporter=lcov ava' },
  ava: { files: [ 'test/index.js' ] },
  dependencies:
   { extend: '3.0.0',
     globby: '^6.1.0',
     meow: '3.7.0',
     mkdirp: '0.5.1',
     'uglify-js': '2.7.5',
     'uglify-js-harmony': '2.6.2' },
  devDependencies:
   { ava: '0.17.0',
     nyc: '^10.0.0',
     proxyquire: '^1.7.10',
     sinon: '^1.17.6' },
  gitHead: '0e97248a14b99682b0ddefb0941236e00d4d3cad',
  dist:
   { integrity: 'sha512-TswzKt4/F+IRFSSKreMCx0xqsGd+acJQxKHP0RIs3C9O/2piSGBLKHAYpdvyUC19GZjU4jMWxdplX8rYM6zQgQ==',
     shasum: '06f219fe14389ce338d7f3ae2913d0cf3c873ed1',
     tarball: 'https://registry.npmjs.org/uglifyjs-folder/-/uglifyjs-folder-1.2.0.tgz' },
  directories: {} }
```

**Comment by ionutvmi** [comment]
```
    throw new JS_Parse_Error
```
You probably have a syntax error in one of the files included in the folder.
Try to check them with a linter

```
uglifyjs-folder platforms/browser/www/Component.js -o platforms/browser/www/Component.js
```
UglifyJS folder was designed to minify folders not individual files.
In this case it says that Component.js is an invalid folder.

**Comment by rchovan** [comment]
Hi, I use NetBeans and colleagues uses IJ Idea. In both programs are our sources error free.  Yes, they have some warnings, but not errors. Could you please extend output informations with filename which has syntax error ?

**Comment by ionutvmi** [comment]
@rchovan this project still uses uglifyjs 2 as the main minifier.
As such if you are trying to minify ES6 it will throw a syntax error as it doesn't recognize the new keywords.

Passing the --es6 or -y parameter for now it's the correct approach.
I do plan to upgrade to uglifyjs 3 soon so this problem should go away.

I will keep this ticket open as a reminder for that.
